apiVersion: v1
kind: Secret
metadata:
  name: pero-secrets
  labels:
    app.kubernetes.io/name: pero-j
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@postgres:5432/soroban_explorer"
